- name: check a number less than 10 or not
  hosts: local
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 4
  tasks:
  - name: is ansible more than 5 sessions
    ansible.builtin.debug:
      msg: "yes, more than 5 sessions"
    when: NUMBER_OF_SESSIONS > 5